# Generated by Django 5.0.6 on 2024-06-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "relevant_documents",
                    models.ManyToManyField(to="selfchatgpt.document"),
                ),
            ],
            options={
                "db_table": "chat_history",
            },
        ),
    ]
