# Generated by Django 5.0.6 on 2024-06-09 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfchatgpt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chathistory",
            options={"verbose_name_plural": "chat histories"},
        ),
        migrations.RemoveField(
            model_name="document",
            name="created_at",
        ),
        migrations.AddField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
