# Generated by Django 5.0.6 on 2024-06-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "selfchatgpt",
            "0002_alter_chathistory_options_remove_document_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Document",
            new_name="VectorDocument",
        ),
    ]
