# Generated by Django 5.0.6 on 2024-06-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("selfchatgpt", "0007_application"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qnapost",
            options={"ordering": ["-created_at"]},
        ),
    ]
